### PR TITLE
Reviews filtered by category and can click to share link

### PR DESCRIPTION
**Pull request by BINQIU1220**

### CODE REVIEW

**Comment by BINQIU1220** [comment]
https://ibb.co/s1thB9b illustration pic

**Comment by dappernerddesigns** [comment]
Hey Bin, while your filtering functionality is showing the reviews by category, the url is not changing. Your component for this is massive and not re usable. I would suggest the sort be a component all of its own so that you can then navigate to a re usable component to display your results. This PR needs to be refactored and then resubmitted. If you are unsure about what these comments mean, by all means put in a help request.

**Comment by BINQIU1220** [comment]
> Hey Bin, while your filtering functionality is showing the reviews by category, the url is not changing. Your component for this is massive and not re usable. I would suggest the sort be a component all of its own so that you can then navigate to a re usable component to display your results. This PR needs to be refactored and then resubmitted. If you are unsure about what these comments mean, by all means put in a help request.

**Comment by elijaharley** [comment]
It looks like you've got some really nice functionality here Bin, it looks like in trying to follow Verity's recommendations your dropdown has stopped showing the categories. I'd suggest implementing a Navbar before continuing as this will make things much easier.

**Pull request merged**
